export const applicationPreparationStyles = {
  form: 'flex flex-col gap-5',
  card: 'flex flex-col gap-3 rounded-[1.4rem] border border-sample-border bg-white p-[1.35rem] shadow-[0_8px_24px_rgb(32_33_36_/_4%)]',
  cardTitle: 'm-0 text-[1.02rem] font-bold tracking-[-0.025em] text-app-ink',
  muted: 'text-sm leading-6 text-slate-600',
  label: 'text-sm font-bold text-app-ink',
  input: 'block min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus-visible:border-emerald-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-700 disabled:cursor-not-allowed disabled:bg-slate-100',
  button: 'inline-flex min-h-10 items-center justify-center rounded-full border border-slate-300 bg-white px-4 py-2 text-sm font-semibold hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-700',
  primary: 'inline-flex min-h-11 items-center justify-center self-start rounded-full bg-emerald-800 px-5 py-2 text-sm font-semibold text-white hover:bg-emerald-900 disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-700',
  warning: 'rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950',
  notice: 'rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm leading-6 text-slate-700',
  status: 'm-0 text-sm leading-6 text-slate-600',
  list: 'flex flex-col gap-3',
  listLink: 'flex flex-col gap-1 rounded-lg text-app-ink no-underline hover:text-emerald-800 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-700',
  moreActions: 'flex flex-wrap items-center gap-3',
  officialLink: 'self-start rounded text-sm font-bold text-emerald-800 underline underline-offset-2 hover:text-emerald-950 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-700',
  details: 'grid gap-2 text-sm [&>div]:grid [&>div]:grid-cols-[minmax(7rem,0.3fr)_1fr] [&>div]:gap-3 [&_dt]:font-bold [&_dt]:text-slate-600 [&_dd]:m-0 [&_dd]:text-app-ink',
  sectionList: 'flex flex-col gap-3',
  sectionItem: 'flex flex-col gap-2 rounded-xl border border-slate-200 p-4',
  sectionHeading: 'flex flex-wrap items-center justify-between gap-2',
  notStarted: 'rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600',
  locator: 'm-0 text-xs leading-5 text-slate-500',
} as const
