import type { AdminMember } from '../../../../domain/entities/AdminMember'

// 화면을 먼저 만드는 단계에서 ViewModel이 쓰는 예시 값입니다. 실제 회원이 아닙니다.
// API가 생기면 이 상수 대신 UseCase 호출 결과를 반환합니다. 테스트용 fixture는 data/fixtures가 따로 맡습니다.
export const adminMembers: AdminMember[] = [
  {
    id: 'example-software',
    companyName: '예시 소프트웨어 주식회사',
    managerEmail: 'manager@company.co.kr',
    isEmailVerified: true,
    profileCompletionPercent: 60,
    recruitmentCount: 1,
    proposalCount: 1,
    joinedOn: '2026-09-01',
    status: 'ACTIVE',
  },
  {
    id: 'databridge',
    companyName: '데이터브릿지 주식회사',
    managerEmail: 'partner@databridge.example',
    isEmailVerified: true,
    profileCompletionPercent: 85,
    recruitmentCount: 1,
    proposalCount: 3,
    joinedOn: '2026-08-12',
    status: 'ACTIVE',
  },
  {
    id: 'greenfoodlab',
    companyName: '그린푸드랩',
    managerEmail: 'hello@greenfoodlab.example',
    isEmailVerified: false,
    profileCompletionPercent: 35,
    recruitmentCount: 1,
    proposalCount: 0,
    joinedOn: '2026-09-03',
    status: 'REPORTED',
  },
  {
    id: 'visionsol',
    companyName: '비전솔루션',
    managerEmail: 'biz@visionsol.example',
    isEmailVerified: true,
    profileCompletionPercent: 70,
    recruitmentCount: 1,
    proposalCount: 2,
    joinedOn: '2026-07-22',
    status: 'REPORTED',
  },
  {
    id: 'acemkt',
    companyName: '(주)에이스마케팅',
    managerEmail: 'ace@acemkt.example',
    isEmailVerified: true,
    profileCompletionPercent: 20,
    recruitmentCount: 0,
    proposalCount: 15,
    joinedOn: '2026-09-04',
    status: 'PROPOSAL_BLOCKED',
  },
  {
    id: 'hanbit',
    companyName: '한빛제조',
    managerEmail: 'contact@hanbit.example',
    isEmailVerified: false,
    profileCompletionPercent: 15,
    recruitmentCount: 0,
    proposalCount: 0,
    joinedOn: '2026-09-05',
    status: 'PENDING',
  },
]
