const focus = 'focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-primary'

export const savedCalendarStyles = {
  page: 'flex min-h-0 flex-1 flex-col bg-white text-app-ink max-chat:min-h-[740px]',
  content: 'flex min-h-0 flex-1 flex-col px-6 pt-4 pb-6 max-chat:px-4',
  filters: 'mt-1 shrink-0 overflow-hidden rounded-2xl border border-sample-border bg-white',
  filterControls: 'grid grid-cols-[minmax(12rem,1.6fr)_minmax(8rem,0.75fr)_minmax(9rem,0.9fr)_minmax(9rem,0.9fr)_auto] items-end gap-3 p-4 max-[1100px]:grid-cols-2 max-chat:grid-cols-1',
  searchField: `flex min-h-12 items-center gap-2 rounded-xl border border-sample-border px-3 text-sample-muted focus-within:border-brand-primary ${focus}`,
  searchInput: 'min-w-0 flex-1 border-0 bg-transparent text-sm text-app-ink placeholder:text-[#9ca3af] focus:outline-0',
  selectField: 'grid min-w-0 gap-1 text-[0.68rem] font-semibold text-sample-muted [&>select]:min-h-8 [&>select]:w-full [&>select]:cursor-pointer [&>select]:border-0 [&>select]:bg-transparent [&>select]:text-sm [&>select]:font-semibold [&>select]:text-app-ink [&>select]:focus:outline-0 [&>select]:focus-visible:outline-2 [&>select]:focus-visible:outline-brand-primary',
  closedToggle: `flex min-h-12 cursor-pointer items-center justify-center gap-2 rounded-xl bg-[#f4f8f5] px-4 text-sm font-semibold whitespace-nowrap text-brand-primary [&>input]:size-4 [&>input]:accent-brand-primary ${focus}`,
  appliedFilters: 'flex min-h-14 flex-wrap items-center gap-2 border-t border-sample-border bg-[#f5f7fa] px-4 py-2 text-xs text-sample-muted',
  filterChip: `inline-flex min-h-8 cursor-pointer items-center gap-1.5 rounded-full border border-sample-border bg-white px-3 text-xs font-medium text-app-ink hover:border-brand-primary hover:text-brand-primary ${focus}`,
  resetFilters: `ml-auto cursor-pointer border-0 bg-transparent px-1 py-1 text-xs font-semibold text-brand-primary underline-offset-4 hover:underline ${focus}`,
  noFilters: 'text-xs text-sample-muted',
  toolbar: 'flex shrink-0 flex-wrap items-center justify-between gap-x-5 gap-y-3 border-b border-sample-border py-4',
  navigation: 'flex min-w-0 flex-wrap items-center gap-3',
  monthSelect: `cursor-pointer rounded-md border border-transparent bg-white py-2 pr-1 text-base font-semibold text-app-ink hover:border-sample-border ${focus}`,
  arrowGroup: 'inline-flex shrink-0 overflow-hidden rounded-md border border-sample-border',
  arrow: `grid size-9 cursor-pointer place-items-center border-r border-sample-border bg-white text-sample-muted last:border-r-0 hover:bg-brand-accent hover:text-brand-primary disabled:cursor-not-allowed disabled:bg-app-canvas disabled:text-[#b0b5b9] ${focus} focus-visible:-outline-offset-2`,
  note: 'flex shrink-0 flex-wrap items-center justify-between gap-2 py-3 text-xs leading-relaxed text-sample-muted',
  scroll: `relative min-h-[200px] flex-1 overflow-auto overscroll-contain border-t border-b border-sample-border [scrollbar-gutter:stable] ${focus} max-chat:h-[520px] max-chat:flex-none`,
  table: 'w-full min-w-[630px] table-fixed border-separate border-spacing-0',
  weekday: 'sticky top-0 z-10 border-b border-sample-border bg-white px-3 py-3 text-left text-xs font-medium',
  cell: 'h-[120px] border-r border-b border-sample-border px-1 py-2 align-top last:border-r-0',
  date: 'mb-2 ml-2 inline-flex size-6 items-center justify-center rounded-full text-xs',
  events: 'm-0 flex list-none flex-col gap-1.5 p-0',
  event: 'flex items-start gap-1.5 rounded-md bg-brand-accent px-1.5 py-1.5 text-xs leading-[1.45] break-words text-[#175d3a]',
  eventBadge: 'mt-px inline-flex min-w-5 shrink-0 items-center justify-center rounded px-1 py-0.5 text-[10px] font-bold leading-none',
  eventBody: 'min-w-0 flex-1',
  eventTitle: 'block font-medium',
  eventOrg: 'mt-1 block text-[10px] text-[#426650]',
  footer: 'm-0 shrink-0 pt-3 text-xs leading-relaxed text-sample-muted',
} as const
