function classes(...groups: string[]) {
  return groups.join(' ')
}

export const pricingPageStyles = {
  page: 'mx-auto flex w-[min(1180px,calc(100%_-_3rem))] min-w-0 flex-col gap-16 pt-[clamp(2.75rem,6vw,5rem)] pb-16 text-app-ink max-chat:w-[calc(100%_-_2rem)] max-chat:gap-12 max-chat:pb-10',
  hero: 'mx-auto flex max-w-[780px] flex-col items-center text-center',
  badge: 'm-0 inline-flex items-center gap-2 rounded-full bg-[#d7efe2] px-4 py-2 text-[0.8rem] font-bold text-[#126742]',
  badgeDot: 'size-1.5 rounded-full bg-brand-primary',
  title: 'mt-6 mb-0 break-keep text-[clamp(2rem,4.5vw,3.6rem)] font-extrabold leading-[1.3] tracking-[-0.065em] [text-wrap:balance]',
  description: 'mt-5 mb-0 max-w-[600px] break-keep text-[clamp(0.95rem,1.6vw,1.1rem)] leading-[1.8] text-sample-muted [text-wrap:pretty]',
  plansSection: 'flex min-w-0 flex-col gap-6',
  plansHeading: 'm-0 break-keep text-center text-[1rem] font-bold leading-relaxed text-[#365947]',
  plansGrid: 'grid min-w-0 grid-cols-1 items-stretch gap-5 min-[1024px]:grid-cols-3',
  planCard: 'relative flex min-w-0 flex-col rounded-[1.75rem] border p-[clamp(1.4rem,3vw,2rem)]',
  regularCard: 'border-sample-border bg-white shadow-[0_8px_30px_rgb(23_68_45_/_4%)]',
  featuredCard: 'border-[#102b22] bg-[#102b22] text-white shadow-[0_14px_40px_rgb(16_43_34_/_12%)]',
  planTop: 'flex flex-wrap items-center justify-between gap-3',
  planEyebrow: 'm-0 text-[0.72rem] font-extrabold tracking-[0.12em]',
  planStatus: 'rounded-full px-3 py-1 text-[0.68rem] font-bold',
  regularStatus: 'bg-[#edf7f1] text-[#286044]',
  featuredStatus: 'bg-[#c8ead8] text-[#102b22]',
  planTitle: 'mt-5 mb-0 text-[1.65rem] font-extrabold tracking-[-0.045em]',
  planDescription: 'mt-3 mb-0 break-keep text-[0.88rem] leading-[1.8] min-[1024px]:min-h-[4.8rem]',
  regularMuted: 'text-sample-muted',
  featuredMuted: 'text-[#c4dfcf]',
  priceBlock: 'mt-7 mb-6 flex flex-col justify-end gap-2 min-[1024px]:min-h-[5.5rem]',
  freePrice: 'm-0 text-[2.85rem] font-extrabold leading-tight tracking-[-0.07em]',
  pendingPrice: 'm-0 break-keep text-[1.7rem] font-extrabold leading-tight tracking-[-0.045em]',
  priceNote: 'm-0 text-[0.75rem] leading-relaxed',
  divider: 'h-px w-full border-0',
  regularDivider: 'bg-[#e1ece5]',
  featuredDivider: 'bg-[#355447]',
  featureHeading: 'mt-6 mb-4 text-[0.8rem] font-bold',
  featureList: 'm-0 flex list-none flex-col gap-3 p-0',
  featureItem: 'flex items-start gap-2.5 text-[0.85rem] leading-[1.7]',
  featureIcon: 'mt-[0.2rem] size-4 shrink-0',
  regularIcon: 'text-brand-primary',
  featuredIcon: 'text-[#b9e5ce]',
  planFooter: 'mt-auto flex flex-col gap-3 pt-8',
  planButton: 'inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-full border-0 px-4 py-3 text-center text-[0.86rem] font-bold no-underline',
  availableButton: 'cursor-pointer bg-brand-primary text-white hover:bg-[#106b48] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-brand-primary',
  regularPendingButton: 'cursor-not-allowed bg-[#edf3ef] text-[#52685c]',
  featuredPendingButton: 'cursor-not-allowed bg-[#c8ead8] text-[#244b37]',
  footerNote: 'm-0 text-center text-[0.7rem] leading-[1.65]',
  releaseNote: 'm-0 break-keep text-center text-[0.78rem] leading-[1.75] text-sample-muted [text-wrap:pretty]',
  valueSection: 'flex flex-col gap-7 rounded-[1.75rem] border border-sample-border bg-white p-[clamp(1.4rem,4vw,2.5rem)]',
  sectionHeading: 'm-0 break-keep text-[clamp(1.4rem,2.8vw,2rem)] font-extrabold leading-[1.4] tracking-[-0.045em]',
  sectionEyebrow: 'mt-0 mb-3 text-[0.72rem] font-extrabold tracking-[0.08em] text-[#147d58]',
  valueGrid: 'grid grid-cols-1 gap-6 min-[720px]:grid-cols-3',
  valueItem: 'flex min-w-0 flex-col items-start gap-3',
  valueNumber: 'grid size-9 place-items-center rounded-xl bg-[#e5f3e9] text-[0.75rem] font-extrabold text-[#126742]',
  valueTitle: 'm-0 text-[1rem] font-bold tracking-[-0.025em]',
  valueDescription: 'm-0 break-keep text-[0.83rem] leading-[1.8] text-sample-muted',
  faqSection: 'mx-auto flex w-full max-w-[820px] flex-col gap-7',
  faqHeader: 'text-center',
  faqDescription: 'mt-3 mb-0 text-[0.9rem] leading-relaxed text-sample-muted',
  faqList: 'flex flex-col gap-3',
  faqItem: 'group rounded-[1.25rem] border border-sample-border bg-white',
  faqQuestion: classes(
    'flex cursor-pointer list-none items-center justify-between gap-4 rounded-[1.25rem] px-6 py-5 text-[0.92rem] font-bold leading-[1.65]',
    'focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-brand-primary [&::-webkit-details-marker]:hidden max-chat:px-5',
  ),
  faqQuestionText: 'min-w-0 flex-1 break-keep',
  faqIcon: 'size-4 shrink-0 text-[#52685c] group-open:rotate-45',
  faqAnswer: 'm-0 break-keep px-6 pb-5 text-[0.85rem] leading-[1.9] text-sample-muted max-chat:px-5',
  closingSection: 'flex flex-col items-center gap-5 rounded-[2rem] border border-[#cce1d4] bg-[#e4f3e9] px-6 py-11 text-center max-chat:py-9',
  closingDescription: 'm-0 max-w-[520px] break-keep text-[0.92rem] leading-[1.8] text-sample-muted',
  closingButton: 'mt-1 inline-flex min-h-12 max-w-full items-center justify-center gap-2 rounded-full bg-brand-primary px-6 py-3 text-[0.88rem] font-bold text-white no-underline hover:bg-[#106b48] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-brand-primary',
  arrowIcon: 'size-4 shrink-0',
} as const
